config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/v1"

  post "/v1", to: "graphql#execute"
  get "/v1", to: "static_page#query"
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end

  def query
    result = MyappSchema.execute params[:query]
    render json: result
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
  def random_from_date
    number = Random.rand(802) + 1
    uri = URI("http://pokeql.com/v1?query={PokemonSpecies(filter:{id:#{number}}){edges{node{pokemons{identifier,sprites{silhouette{male{front}}normal{male{front}}}}}}}}")
    data = Net::HTTP.get_response(uri)

    JSON.parse(data.body).with_indifferent_access[:data][:PokemonSpecies][:edges].first[:node][:pokemons].first
  end
end

app/views/static_page/_whos_that_pokemon.html.erb
<div id="whos-that-pokemon">
  <div id="silhouette">
    <div>
      Who's that Pokemon?
    </div>

    <div>
      <%= image_tag pokemon[:sprites][:silhouette][:male][:front] %> 
    </div>

    <div>
      (click image to reveal)
    </div>
  </div>

  <div id="pokemon">
    <div>
      It's <%= pokemon[:identifier].capitalize %>!
    </div>

    <div>
      <%= image_tag pokemon[:sprites][:normal][:male][:front] %> 
    </div>
  </div>
</div>

app/views/static_page/home.html.erb
<h3>
  PokeQL: A Pokemon API using GraphQL
</h3>

<div class="query-sandbox">
  <%= link_to "Query Tester", graphiql_rails_url %>
</div>

<div>
  Requests should be made using <%= Rails.application.config.url %>/v1
</div>

<div class="notice">
  This API is in beta so endpoints may be changed without notice.
</div>

<%= render "static_page/whos_that_pokemon", pokemon: random_from_date %>

<div>
  <div>
    Data sourced from <%= link_to "pokeapi.co", "//pokeapi.co" %>
  </div>

  <div>
    PokeQL is in no way affiliated or endorsed by PokeAPI.
  </div>
</div>

<div class="signature">
  Built by <%= link_to "Josh Dunn", "//github.com/joshddunn" %>
</div>